#ifndef SQRTDEMO_PROJECTCONFIG_H
#define SQRTDEMO_PROJECTCONFIG_H
#define PROJECT_VERSION "@CPROJECT_VERSION"
/* #undef USE_MYMATH */
#define PROJECT_VERSION_MAJOR 1
#define PROJECT_VERSION_MINOR 0
#define PROJECT_VERSION_PATCH 0
#endif
